name: Build LaTeX document
on: [push]
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v2
        with:
          root_file: Cookbook.tex
      - name: Upload GitHub Artifact
        uses: actions/upload-artifact@v2
        with:
          name: Cookbook
          path: Cookbook.pdf
      - name: Upload Final PDF to AWS S3
        uses: zdurham/s3-upload-github-action@master
        # if: github.ref == 'refs/heads/master'
        with:
          args: --acl public-read
        env:
          FILE: ./Cookbook.pdf
          AWS_REGION: 'us-west-2'
          S3_BUCKET: ${{ secrets.AWS_BUCKET }}
          S3_KEY: 'cookbook.pdf'
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
